# Generated by Django 4.1.7 on 2023-12-14 06:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_trainingschedule_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_days', models.PositiveIntegerField(default=0)),
                ('attendance_upload', models.FileField(blank=True, null=True, upload_to='training_attendance_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xls', 'xlsx'])])),
                ('assessment_upload', models.FileField(blank=True, null=True, upload_to='training_assessment_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xls', 'xlsx'])])),
                ('feedback_upload', models.FileField(blank=True, null=True, upload_to='training_feedback_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xls', 'xlsx'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='training.employee')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='training.trainingschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_code', models.CharField(blank=True, help_text='If left blank, a code would be generated automatically.', max_length=255, null=True, verbose_name='Trainer Code')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], max_length=20)),
                ('expertise', models.TextField(blank=True, null=True)),
                ('document', models.FileField(upload_to='trainer_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='training.designation')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_program_code', models.CharField(blank=True, help_text='If left blank, a code would be generated automatically.', max_length=255, unique=True, verbose_name='External Program Code')),
                ('organizer', models.CharField(max_length=255, verbose_name='Name of Organizer')),
                ('place', models.CharField(max_length=255, verbose_name='Place of Training')),
                ('duration', models.PositiveIntegerField(help_text='Enter duration in number of Days')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('training_area', models.CharField(max_length=255, verbose_name='Training Area/Focus')),
                ('document', models.FileField(upload_to='external_training_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xls', 'xlsx'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list_of_attendees', models.ManyToManyField(to='training.employee')),
            ],
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='training.trainer'),
        ),
    ]
