# Generated by Django 4.1.7 on 2023-12-14 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_trainingattendance_trainer_externaltraining_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingattendance',
            unique_together={('training', 'employee')},
        ),
    ]
