# Generated by Django 4.1.7 on 2023-12-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_trainingattendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtype',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
