# Generated by Django 4.1.7 on 2024-01-07 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_alter_trainingtype_options_trainingtype_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingschedule',
            name='no_trainees',
        ),
    ]
