# Generated by Django 4.1.7 on 2024-01-09 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_remove_trainingschedule_no_trainees'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='training.employee')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='training.trainingschedule')),
            ],
            options={
                'unique_together': {('training', 'employee')},
            },
        ),
    ]
